# -*- coding: utf-8 -*-
"""PCS5029_Transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1490Tz6bWqKqqWY5mpNaRuXaOVIb66SbP
"""

TOKEN_HUGGING_FACE = "TOKEN_HERE"

!huggingface-cli login

# ## 🧩 Conjuntos de tarefas — DoSMi v2 e Expertise Map

"""# Benchmark extended"""

expertise_map = {
    "qa_factual": [
        {"question": "Quem escreveu a peça Hamlet?", "expected": "William Shakespeare"},
        {"question": "Qual é o maior planeta do sistema solar?", "expected": "Júpiter"},
        {"question": "Em que continente fica o Egito?", "expected": "África"},
        {"question": "Quem pintou a Mona Lisa?", "expected": "Leonardo da Vinci"},
        {"question": "Qual é o idioma oficial do Japão?", "expected": "Japonês"},
        {"question": "Em que país nasceu Albert Einstein?", "expected": "Alemanha"},
        {"question": "Quantos dias há em um ano bissexto?", "expected": "366"},
        {"question": "Qual elemento químico tem símbolo O?", "expected": "Oxigênio"},
        {"question": "Qual é a capital do Canadá?", "expected": "Ottawa"},
        {"question": "Quem descobriu o Brasil?", "expected": "Pedro Álvares Cabral"},
    ],
    "math_gsm8k": [
        {"question": "Se João tem 3 maçãs e compra mais 2, quantas ele tem agora?", "expected": "5"},
        {"question": "Qual é o resultado de 12 × 8?", "expected": "96"},
        {"question": "Um trem parte às 10h e chega às 13h30. Quantas horas durou a viagem?", "expected": "3.5"},
        {"question": "Qual é a metade de 144?", "expected": "72"},
        {"question": "Se 5x = 20, qual é o valor de x?", "expected": "4"},
        {"question": "Qual é o quadrado de 15?", "expected": "225"},
        {"question": "Maria tinha 10 reais e gastou 4. Quanto sobrou?", "expected": "6"},
        {"question": "Se uma pizza tem 8 fatias e João come 3, quantas sobram?", "expected": "5"},
        {"question": "O triplo de 7 é quanto?", "expected": "21"},
        {"question": "Quanto é 10% de 250?", "expected": "25"},
    ],
    "code_mbpp": [
        {"question": "Escreva uma função Python que soma dois números.", "expected": "def soma(a,b): return a+b"},
        {"question": "Escreva uma função que verifica se um número é par.", "expected": "def is_even(n): return n%2==0"},
        {"question": "Implemente uma função que calcula o fatorial de n.", "expected": "def fatorial(n): return 1 if n==0 else n*fatorial(n-1)"},
        {"question": "Crie uma função que retorna o maior de dois números.", "expected": "def maior(a,b): return a if a>b else b"},
        {"question": "Crie uma função que inverte uma string.", "expected": "def inverte(s): return s[::-1]"},
        {"question": "Escreva uma função que retorna se um número é primo.", "expected": "def is_prime(n): return all(n%i for i in range(2,int(n**0.5)+1)) and n>1"},
        {"question": "Escreva uma função que retorna o quadrado de um número.", "expected": "def quadrado(x): return x**2"},
        {"question": "Escreva uma função que calcula a média de uma lista.", "expected": "def media(lst): return sum(lst)/len(lst)"},
        {"question": "Crie uma função que concatena duas strings.", "expected": "def concatena(a,b): return a+b"},
        {"question": "Escreva uma função que conta vogais em uma string.", "expected": "def conta_vogais(s): return sum(c.lower() in 'aeiou' for c in s)"},
    ],
    "qa_fin": [
        {"question": "Qual é o código ISIN do ITUB4?", "expected": "BRITUBACNPR1"},
        {"question": "Qual é a moeda oficial do Brasil?", "expected": "real"},
        {"question": "O que significa o termo 'free float'?", "expected": "percentual de ações em livre circulação"},
        {"question": "Qual é o índice de ações mais famoso da B3?", "expected": "Ibovespa"},
        {"question": "Qual é a função de um 'market maker'?", "expected": "fornecer liquidez ao mercado"},
        {"question": "O que é o CDI?", "expected": "Certificado de Depósito Interbancário"},
        {"question": "O que é uma ação preferencial?", "expected": "ação com preferência em dividendos"},
        {"question": "Qual é a função do Banco Central do Brasil?", "expected": "controlar a política monetária"},
        {"question": "O que é um fundo de investimento?", "expected": "veículo coletivo de aplicação financeira"},
        {"question": "Qual é a sigla da moeda americana?", "expected": "USD"},
    ],
}

# Microtarefas — DoSMi v2
datasets_dosmi = {
    "qa_curta": [
        {"question": "Quem escreveu Dom Quixote?", "expected": "Miguel de Cervantes"},
        {"question": "Qual é a capital da França?", "expected": "Paris"},
        {"question": "Quem pintou Guernica?", "expected": "Pablo Picasso"},
        {"question": "Qual é o idioma oficial da China?", "expected": "Chinês"},
        {"question": "Quem descobriu a América?", "expected": "Cristóvão Colombo"},
    ],
    "calculo_rapido": [
        {"question": "Quanto é 23 + 57?", "expected": "80"},
        {"question": "Quanto é 15 × 6?", "expected": "90"},
        {"question": "Se tenho 20 e gasto 5, quanto resta?", "expected": "15"},
        {"question": "Quanto é 10% de 300?", "expected": "30"},
        {"question": "Quanto é 100 ÷ 4?", "expected": "25"},
    ],
    "codigo_trivial": [
        {"question": "Escreva uma função Python que retorna o quadrado de x.", "expected": "def quadrado(x): return x**2"},
        {"question": "Crie uma função que soma dois números.", "expected": "def soma(a,b): return a+b"},
        {"question": "Escreva uma função que verifica se um número é par.", "expected": "def is_even(n): return n%2==0"},
        {"question": "Crie uma função que inverte uma string.", "expected": "def inverte(s): return s[::-1]"},
        {"question": "Escreva uma função que conta vogais em uma string.", "expected": "def conta_vogais(s): return sum(c.lower() in 'aeiou' for c in s)"},
    ],
    "needle_test": [
        {"question": "No texto '123 token 999', qual número vem após a palavra token?", "expected": "999"},
        {"question": "No texto 'A B C D token Z', qual letra vem após token?", "expected": "Z"},
        {"question": "Encontre o número escondido: 'abc token 42 xyz'", "expected": "42"},
        {"question": "Qual número aparece depois de token: 'foo token 17 bar'?", "expected": "17"},
        {"question": "Qual palavra aparece após token: 'um token dois'?", "expected": "dois"},
    ],
}


# # 🧠 Benchmark — Modelos GPT (MoE vs Densos)
# Avaliação de throughput, latência e acurácia em micro e macrotarefas
# Autor: Renan de Luca Avila — PCS5029 / EPUSP


import torch, gc, time, csv
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from pathlib import Path

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
OUT_DIR = Path("results"); OUT_DIR.mkdir(exist_ok=True)


# ## ⚙️ Configuração de modelos e quantização NF4


MODELS = {
    "MoE": [
        "deepseek-ai/DeepSeek-Coder-6.7B-base",
        "mistralai/Mixtral-8x7B-Instruct-v0.1",
    ],
    "Dense": [
        "google/gemma-7b-it",
        "openchat/openchat-3.5-0106",
    ],
}

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

MAX_NEW_TOKENS = 128

# ## 🔧 Funções auxiliares

# %%
def family_from_name(name: str) -> str:
    n = name.lower()
    if any(k in n for k in ["mixtral", "deepseek", "moe"]):
        return "MoE"
    return "Dense"

def compute_correct(pred, exp):
    if not pred or not exp:
        return 0.0
    p, e = pred.strip().lower(), exp.strip().lower()
    return float(e in p or p in e)

def clear_gpu():
    gc.collect()
    torch.cuda.empty_cache()

def timed_generation(model, tokenizer, prompt, max_new_tokens=128):
    t0 = time.time()
    with torch.no_grad():
        inputs = tokenizer(prompt, return_tensors="pt").to(DEVICE)
        gen = model.generate(**inputs, max_new_tokens=max_new_tokens)
        output = tokenizer.decode(gen[0], skip_special_tokens=True)
    latency = time.time() - t0
    n_out = len(tokenizer(output)["input_ids"])
    tokens_per_s = n_out / latency if latency > 0 else 0
    return output, latency, tokens_per_s


# ## 🚀 Função genérica de benchmark


def run_benchmark(model_name, dataset_dict, csv_path):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=torch.float16,
    )
    family = family_from_name(model_name)

    with open(csv_path, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "model","family","task","question","expected","answer","correct","latency","tokens_s"
        ])
        if f.tell() == 0:
            writer.writeheader()

        for task_name, items in dataset_dict.items():
            for item in tqdm(items, desc=f"{model_name} — {task_name}"):
                q, exp = item["question"], item["expected"]
                try:
                    out, lat, tps = timed_generation(model, tokenizer, q, MAX_NEW_TOKENS)
                    correct = compute_correct(out, exp)
                except Exception as e:
                    out, lat, tps, correct = str(e), float("nan"), float("nan"), 0
                writer.writerow({
                    "model": model_name,
                    "family": family,
                    "task": task_name,
                    "question": q,
                    "expected": exp,
                    "answer": out,
                    "correct": correct,
                    "latency": lat,
                    "tokens_s": tps,
                })
    del model, tokenizer
    clear_gpu()


# ## 🧠 Execução — DoSMi v2 e Expertise Map

# %%
CSV_DOSMI = OUT_DIR / "benchmark_dosmi_v2.csv"
CSV_EXP = OUT_DIR / "benchmark_expertise.csv"

for fam, model_list in MODELS.items():
    for model_name in model_list:
        print(f"===== Rodando {model_name} — DoSMi v2 =====")
        run_benchmark(model_name, datasets_dosmi, CSV_DOSMI)
        print(f"===== Rodando {model_name} — Expertise Map =====")
        run_benchmark(model_name, expertise_map, CSV_EXP)

print(f"Benchmarks concluídos! Arquivos salvos em:\n  - {CSV_DOSMI}\n  - {CSV_EXP}")